name: Griswold
main: com.github.toxuin.Griswold
version: 0.052
author: toxuin
description: Creates a man, who repairs stuff.

commands:
  blacksmith:
    description: does all the work for Griswold plugin
    aliases: bsmith

permissions:
    griswold.*:
        description: Gives FULL ACCESS, be careful!
        children:
            griswold.admin: true
            griswold.tools: true
            griswold.armor: true
            griswold.enchant: true
    griswold.admin:
        description: Allows you to manage the blacksmiths
        default: op
    griswold.tools:
        description: Allows you to repair tools and weapons 
        default: op
    griswold.armor:
        description: Allows you to repair armor
        default: op
    griswold.enchant:
        description: Allows you to add enchantments
        default: op

softdepend: [Vault]